name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:latest

      - name: Add EC2 Host to Known Hosts (Fix SSH Issues)
        run: 
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Ensure Docker is running
            sudo systemctl start docker || true

            # Fix Docker permissions issue
            sudo chmod 666 /var/run/docker.sock || true

            # Stop and remove existing container (force to avoid errors)
            docker stop node-app || true
            docker rm -f node-app || true

            # Pull latest image
            docker pull ${{ secrets.DOCKER_USERNAME }}/node-app:latest

            # Run the container on port 3000
            docker run -d --name node-app -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/node-app:latest
