name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:latest

      - name: Decode SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > private_key.pem
          chmod 600 private_key.pem

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: "${{ secrets.EC2_SSH_KEY }}"
          script: |
            # Install Docker if not installed
            if ! [ -x "$(command -v docker)" ]; then
              sudo yum update -y
              sudo amazon-linux-extras enable docker
              sudo yum install -y docker
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

            # Ensure Docker is running
            sudo systemctl start docker || true

            # Fix Docker permissions
            sudo usermod -aG docker ec2-user
            sudo chmod 666 /var/run/docker.sock || true

            # Clean up existing container
            sudo docker stop node-app || true
            sudo docker rm -f node-app || true

            # Pull latest image
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/node-app:latest

            # Run the container on port 5000
            sudo docker run -d --name node-app -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/node-app:latest

            echo "Deployment successful"
